### ISSUE TITLE
Offsets should be in UTC

### ISSUE THREAD

**Issue by woodpav** [vahnag/react-timezone#25]
GMT is a timezone and UTC is a time standard. 

They are sometimes used interchangeably (i.e. GMT is UTC+0), but UTC is now the scientific standard (and thus the standard for timezone offsets). England is (sometimes) on GMT but no physical place is ever on UTC.

https://www.timeanddate.com/time/gmt-utc-time.html

From https://en.wikipedia.org/wiki/Greenwich_Mean_Time:

> GMT was formerly used as the international civil time standard, now superseded in that function by Coordinated Universal Time (UTC).

Edit: JavaScript lists offsets in GMT but JavaScript is wrong.

Edit 2: 

> Timezones are borrowed from Google Calendar.

Just checked Google Calendar. They are also in GMT offsets. Gah!

**Comment by vahnag** [comment]
Hey, thanks for the issue. As far as I know it's the GMT timezone that's considered the 0 timezone in everyday life and UTC is like the time standard. So I think that's why Google too shows it in GMT.

But anyway it's good to give a choice for the users of this library to show in whatever offset they feel like fits best for their target audience.

btw this is a great and fun article on timezones are love https://zachholman.com/talk/utc-is-enough-for-everyone-right

>It’s important to note that UTC is not GMT. GMT is Greenwich Mean Time, which historically was the center of time in the world. They both have an offset of 00:00. But you shouldn’t use GMT on your server, for example, because UTC is a standard, but GMT is a timezone. People actually live in locations whose time is GMT; UTC isn’t directly used by people (unless they’re really weird).

>This may sound like such a small difference of wankery, but the more relevant part is that some users of GMT observe Daylight Saving Time (but not all). UTC has no concept of Daylight Saving Time at all. So if you base everything in GMT, well, who knowssss what will happen.
